# Pydantic schemas will be defined here per domain module.
from app.schemas.auth import Token, UserRead, UserRegister
from app.schemas.dashboard import (
    DashboardRecommendation,
    LatestScoreSummary,
    LatestSnapshotSummary,
    MetricCards,
    PortfolioAlertProject,
    PortfolioDashboardResponse,
    PortfolioProjectSummary,
    ProjectDashboardResponse,
    ProjectSeries,
    ProjectSummary,
    RecentProjectSummary,
    SeriesPoint,
)
from app.schemas.metric_snapshot import (
    MetricSnapshotCreate,
    MetricSnapshotListItem,
    MetricSnapshotListResponse,
    MetricSnapshotRead,
    MetricSnapshotUpdate,
)
from app.schemas.report import ReportListItem, ReportListResponse, ReportRead
from app.schemas.saas_project import (
    SaasProjectCreate,
    SaasProjectListItem,
    SaasProjectListResponse,
    SaasProjectRead,
    SaasProjectUpdate,
)
from app.schemas.saas_score import (
    SaasScoreListItem,
    SaasScoreListResponse,
    SaasScoreRead,
    ScoreAlertItem,
    ScoreDiagnosticItem,
    ScoreRecommendationItem,
)

__all__ = [
    "DashboardRecommendation",
    "LatestScoreSummary",
    "LatestSnapshotSummary",
    "MetricCards",
    "MetricSnapshotCreate",
    "MetricSnapshotListItem",
    "MetricSnapshotListResponse",
    "MetricSnapshotRead",
    "MetricSnapshotUpdate",
    "PortfolioAlertProject",
    "PortfolioDashboardResponse",
    "PortfolioProjectSummary",
    "ProjectDashboardResponse",
    "ProjectSeries",
    "ProjectSummary",
    "RecentProjectSummary",
    "ReportListItem",
    "ReportListResponse",
    "ReportRead",
    "SaasProjectCreate",
    "SaasProjectListItem",
    "SaasProjectListResponse",
    "SaasProjectRead",
    "SaasProjectUpdate",
    "SaasScoreListItem",
    "SaasScoreListResponse",
    "SaasScoreRead",
    "ScoreAlertItem",
    "ScoreDiagnosticItem",
    "ScoreRecommendationItem",
    "SeriesPoint",
    "Token",
    "UserRead",
    "UserRegister",
]
