# Pydantic schemas will be defined here per domain module.
from app.schemas.ai_analysis import (
    AiAnalysisCreate,
    AiAnalysisListItem,
    AiAnalysisListResponse,
    AiAnalysisRead,
)
from app.schemas.ai_key import (
    AiProviderKeyCreate,
    AiProviderKeyListResponse,
    AiProviderKeyRead,
    AiProviderKeyUpdate,
    AiProviderKeyVerifyRequest,
    AiProviderKeyVerifyResponse,
)
from app.schemas.auth import Token, UserRead, UserRegister
from app.schemas.chat_message import (
    ChatMessageListResponse,
    ChatMessageRead,
    SendChatMessageRequest,
    SendChatMessageResponse,
)
from app.schemas.conversation import (
    ConversationCreate,
    ConversationListResponse,
    ConversationRead,
    ConversationUpdate,
)
from app.schemas.dashboard import (
    DashboardRecommendation,
    LatestScoreSummary,
    LatestSnapshotSummary,
    MetricCards,
    PortfolioAlertProject,
    PortfolioDashboardResponse,
    PortfolioProjectSummary,
    ProjectDashboardResponse,
    ProjectSeries,
    ProjectSummary,
    RecentProjectSummary,
    SeriesPoint,
)
from app.schemas.metric_snapshot import (
    MetricSnapshotCreate,
    MetricSnapshotListItem,
    MetricSnapshotListResponse,
    MetricSnapshotRead,
    MetricSnapshotUpdate,
)
from app.schemas.report import ReportListItem, ReportListResponse, ReportRead
from app.schemas.saas_project import (
    SaasProjectCreate,
    SaasProjectListItem,
    SaasProjectListResponse,
    SaasProjectRead,
    SaasProjectUpdate,
)
from app.schemas.saas_score import (
    SaasScoreListItem,
    SaasScoreListResponse,
    SaasScoreRead,
    ScoreAlertItem,
    ScoreDiagnosticItem,
    ScoreRecommendationItem,
)

__all__ = [
    "AiAnalysisCreate",
    "AiAnalysisListItem",
    "AiAnalysisListResponse",
    "AiAnalysisRead",
    "AiProviderKeyCreate",
    "AiProviderKeyListResponse",
    "AiProviderKeyRead",
    "AiProviderKeyUpdate",
    "AiProviderKeyVerifyRequest",
    "AiProviderKeyVerifyResponse",
    "ChatMessageListResponse",
    "ChatMessageRead",
    "ConversationCreate",
    "ConversationListResponse",
    "ConversationRead",
    "ConversationUpdate",
    "DashboardRecommendation",
    "LatestScoreSummary",
    "LatestSnapshotSummary",
    "MetricCards",
    "MetricSnapshotCreate",
    "MetricSnapshotListItem",
    "MetricSnapshotListResponse",
    "MetricSnapshotRead",
    "MetricSnapshotUpdate",
    "PortfolioAlertProject",
    "PortfolioDashboardResponse",
    "PortfolioProjectSummary",
    "ProjectDashboardResponse",
    "ProjectSeries",
    "ProjectSummary",
    "RecentProjectSummary",
    "ReportListItem",
    "ReportListResponse",
    "ReportRead",
    "SaasProjectCreate",
    "SaasProjectListItem",
    "SaasProjectListResponse",
    "SaasProjectRead",
    "SaasProjectUpdate",
    "SaasScoreListItem",
    "SaasScoreListResponse",
    "SaasScoreRead",
    "ScoreAlertItem",
    "ScoreDiagnosticItem",
    "ScoreRecommendationItem",
    "SendChatMessageRequest",
    "SendChatMessageResponse",
    "SeriesPoint",
    "Token",
    "UserRead",
    "UserRegister",
]
