"""use_partial_index_for_saas_projects

Revision ID: 0be93612fe34
Revises: 99ea31091c6a
Create Date: 2026-06-13 12:14:42.598165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be93612fe34'
down_revision: Union[str, None] = '99ea31091c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saas_projects_owner_slug', 'saas_projects', type_='unique')
    op.create_index('uq_saas_projects_owner_slug', 'saas_projects', ['owner_id', 'slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_saas_projects_owner_slug', table_name='saas_projects', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint('uq_saas_projects_owner_slug', 'saas_projects', ['owner_id', 'slug'])
    # ### end Alembic commands ###
