"""add_chatgpt_web_accounts

Revision ID: 75d7f1ce681e
Revises: 7ce0eff466b0
Create Date: 2026-06-14 18:10:14.012056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d7f1ce681e'
down_revision: Union[str, None] = '7ce0eff466b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatgpt_web_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('encrypted_password', sa.String(length=1024), nullable=True),
    sa.Column('encrypted_session_token', sa.String(length=2048), nullable=True),
    sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chatgpt_web_accounts_active_priority', 'chatgpt_web_accounts', ['is_active', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chatgpt_web_accounts_active_priority', table_name='chatgpt_web_accounts')
    op.drop_table('chatgpt_web_accounts')
    # ### end Alembic commands ###
