"""add_competitors_and_acquisition_strategy

Revision ID: 99ea31091c6a
Revises: 0006
Create Date: 2026-06-11 12:05:25.166452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ea31091c6a'
down_revision: Union[str, None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_projects', sa.Column('competitors', sa.Text(), nullable=True))
    op.add_column('saas_projects', sa.Column('acquisition_strategy', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saas_projects', 'acquisition_strategy')
    op.drop_column('saas_projects', 'competitors')
    # ### end Alembic commands ###
