"""simplify_metrics

Revision ID: c676191521ad
Revises: 0003
Create Date: 2026-06-10 12:25:19.882699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c676191521ad'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saas_metric_snapshots', 'marketing_spend')
    op.drop_column('saas_metric_snapshots', 'new_paying_customers')
    op.drop_column('saas_metric_snapshots', 'growth_rate')
    op.drop_column('saas_metric_snapshots', 'active_users')
    op.drop_column('saas_metric_snapshots', 'ltv_cac_ratio')
    op.drop_column('saas_metric_snapshots', 'conversion_rate')
    op.drop_column('saas_metric_snapshots', 'runway_months')
    op.drop_column('saas_metric_snapshots', 'payback_months')
    op.drop_column('saas_metric_snapshots', 'net_profit')
    op.drop_column('saas_metric_snapshots', 'gross_profit')
    op.drop_column('saas_metric_snapshots', 'churned_customers')
    op.drop_column('saas_metric_snapshots', 'burn_rate')
    op.drop_column('saas_metric_snapshots', 'new_users')
    op.drop_column('saas_metric_snapshots', 'ltv')
    op.drop_column('saas_metric_snapshots', 'monthly_revenue')
    op.drop_column('saas_metric_snapshots', 'nps')
    op.drop_column('saas_metric_snapshots', 'arr')
    op.drop_column('saas_metric_snapshots', 'cash_available')
    op.drop_column('saas_metric_snapshots', 'support_tickets')
    op.drop_column('saas_metric_snapshots', 'avg_session_minutes')
    op.drop_column('saas_metric_snapshots', 'uptime_percentage')
    op.drop_column('saas_metric_snapshots', 'arpu')
    op.drop_column('saas_metric_snapshots', 'critical_bugs')
    op.drop_column('saas_metric_snapshots', 'retention_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saas_metric_snapshots', sa.Column('retention_rate', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('critical_bugs', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('arpu', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('uptime_percentage', sa.NUMERIC(precision=6, scale=3), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('avg_session_minutes', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('support_tickets', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('cash_available', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('arr', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('nps', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('monthly_revenue', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('ltv', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('new_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('burn_rate', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('churned_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('gross_profit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('net_profit', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('payback_months', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('runway_months', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('conversion_rate', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('ltv_cac_ratio', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('active_users', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('growth_rate', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('new_paying_customers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('saas_metric_snapshots', sa.Column('marketing_spend', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
